import { cached } from './cache'
import { supabase } from './supabase'
import { COURSE_KEYS, PROGRAM_KEYS, pickMeta } from './formSchema'
import { answersToValues, planAnswerWrite, questionIdOf } from './validation'

// Re-exported for callers that treat this module as the submissions API.
export { answersToValues }

/** The one cycle currently accepting feedback, or null. Cached 5 min. */
export const loadActiveCycle = cached(async function () {
  const { data, error } = await supabase
    .from('academic_cycles')
    .select('id, label, opens_at, closes_at')
    .eq('is_active', true)
    .maybeSingle()

  if (error) throw new Error(error.message)
  return data
}, 5 * 60_000)

/**
 * One cycle by id.
 *
 * A response belongs to the cycle it was submitted in, which is not necessarily
 * the active one: FR-16 makes a past cycle read-only, and FR-17 lets its owner
 * still open it. Judging that by the ACTIVE cycle tells a respondent editing
 * last year's feedback that it closes next November.
 */
export async function loadCycleById(cycleId) {
  if (!cycleId) return null

  const { data, error } = await supabase
    .from('academic_cycles')
    .select('id, label, opens_at, closes_at')
    .eq('id', cycleId)
    .maybeSingle()

  if (error) throw new Error(error.message)
  return data
}

export function cycleIsOpen(cycle) {
  if (!cycle) return false
  const now = Date.now()
  return now >= new Date(cycle.opens_at).getTime() &&
    now < new Date(cycle.closes_at).getTime()
}

/** FR-17: the signed-in user's submissions for a cycle, newest first. Cached 30 s. */
export const loadMySubmissions = cached(async function (userId, cycleId) {
  const { data, error } = await supabase
    .from('responses')
    .select('id, program, course_title, submitted_at, updated_at')
    .eq('user_id', userId)
    .eq('cycle_id', cycleId)
    .order('updated_at', { ascending: false })

  if (error) throw new Error(error.message)
  return data ?? []
}, 30_000)

/**
 * Loads one response plus its answers, shaped into the form's value map.
 *
 * Answers are keyed by question_version_id, but the form renders each question's
 * CURRENT version. When an admin rewords a question, those two ids diverge, so a
 * naive version-id lookup would leave the field blank and the respondent would
 * appear to have never answered it — losing their choice the moment they resave
 * (FR-16, FR-17).
 *
 * So answers are re-keyed by question identity: the stored value is carried onto
 * whichever version the form is showing now. The stored row itself is untouched
 * and still points at the wording that was actually answered, which is what
 * keeps historical analytics honest (FR-31).
 *
 * An answer whose question has since been soft-deleted has no rendered field and
 * is simply dropped from the value map — correct, since there is nothing to edit.
 */
export async function loadResponse(responseId, questions = null) {
  const [{ data: response, error }, { data: answers, error: aError }] = await Promise.all([
    supabase
      .from('responses')
      .select('id, user_id, form_id, cycle_id, program, course_title, submitted_at, updated_at')
      .eq('id', responseId)
      .maybeSingle(),
    supabase
      .from('answers')
      .select(
        `question_version_id, value_numeric, value_text, value_options,
         question_versions!inner ( question_id )`,
      )
      .eq('response_id', responseId),
  ])

  if (error) throw new Error(error.message)
  if (!response) return null
  if (aError) throw new Error(aError.message)

  const rows = remapAnswersToCurrentVersions(answers ?? [], questions)

  // Passing the questions lets answersToValues tell a single_select from a
  // one-choice multi_select by type instead of guessing from array length.
  const byVersionId = questions
    ? new Map(questions.map((q) => [q.versionId, q]))
    : null

  return { response, values: answersToValues(rows, byVersionId) }
}

/**
 * Rewrites each answer's question_version_id to the version the form is
 * currently rendering for that same question.
 *
 * Pure apart from its inputs; exported for the unit tests.
 */
export function remapAnswersToCurrentVersions(answers, questions) {
  if (!questions) return answers

  const currentVersionByQuestionId = new Map(questions.map((q) => [q.id, q.versionId]))

  return answers
    .map((row) => {
      const questionId = questionIdOf(row)

      // No question_id (older shape) means we cannot remap; keep as-is.
      if (!questionId) return row

      const currentVersionId = currentVersionByQuestionId.get(questionId)
      // Question no longer on the live form (soft-deleted): drop it.
      if (!currentVersionId) return null

      return { ...row, question_version_id: currentVersionId }
    })
    .filter(Boolean)
}

/**
 * Creates or updates a submission (FR-12, FR-15, FR-16).
 *
 * The one-per-course rule lives in a unique index on
 * (user_id, cycle_id, course_key), where course_key is generated by Postgres.
 * We cannot upsert on a generated column, so:
 *   - editing an existing response -> update by id
 *   - new submission               -> insert, and translate a 23505 unique
 *     violation into a load-and-edit prompt rather than an opaque failure
 *
 * That keeps Postgres as the single source of truth for the rule: two tabs
 * racing the same course produce one row and one clear message, not a duplicate.
 */
export async function saveSubmission({
  responseId,
  form,
  cycle,
  questions,
  values,
}) {
  const program = pickMeta(questions, values, PROGRAM_KEYS)
  const courseTitle = pickMeta(questions, values, COURSE_KEYS)

  // Editing needs the stored rows to plan against — two things live only there
  // and cannot be rebuilt from the form: answers to questions since soft-deleted,
  // and the version each answer was given against (FR-31, FR-32). A brand-new
  // submission has none, so it skips the read entirely — which is the whole herd
  // (everyone submitting fresh when a cycle opens), now a single round trip.
  let existing = []
  if (responseId) {
    const { data, error } = await supabase
      .from('answers')
      .select(
        `id, question_version_id, value_numeric, value_text, value_options,
         question_versions!inner ( question_id )`,
      )
      .eq('response_id', responseId)
    if (error) throw translateSaveError(error)
    existing = data ?? []
  }

  const { deleteIds, insertRows } = planAnswerWrite(existing, questions, values)

  // One transaction: upsert the response, delete changed/removed answers, insert
  // the new ones. Atomic, so a mid-save timeout can't leave a response with no
  // answers that the unique-per-course index then refuses to let the user retry.
  const { data: id, error } = await supabase.rpc('save_submission', {
    p_response_id: responseId ?? null,
    p_form_id: form.id,
    p_cycle_id: cycle.id,
    p_program: program,
    p_course_title: courseTitle,
    p_delete_ids: deleteIds,
    p_insert_rows: insertRows,
  })
  if (error) throw translateSaveError(error)
  loadMySubmissions.bust()
  return id
}

/** FR-16: a respondent may withdraw a mis-filed submission before close. */
export async function deleteSubmission(responseId) {
  const { error } = await supabase.from('responses').delete().eq('id', responseId)
  if (error) throw translateSaveError(error)
  loadMySubmissions.bust()
}

/**
 * Turns Postgres/PostgREST errors into something a respondent can act on.
 * `code` is preserved so callers can branch (the form offers "edit it instead"
 * on a duplicate).
 */
export function translateSaveError(error) {
  const code = error.code ?? ''
  let message = error.message ?? 'Something went wrong while saving.'

  if (code === '23505') {
    message =
      'You have already submitted feedback for this course in this cycle. ' +
      'Open your existing submission to change your answers.'
  } else if (code === '42501' || /row-level security/i.test(message)) {
    // The edit window closing mid-session is the common cause.
    message =
      'This feedback cycle is closed, so submissions can no longer be changed. ' +
      'Reload the page to see the latest status.'
  }

  const wrapped = new Error(message)
  wrapped.code = code
  return wrapped
}
