import { supabase } from './supabase'
import { COURSE_KEYS, PROGRAM_KEYS, pickMeta } from './formSchema'
import { answersToValues, toAnswerRow } from './validation'

// Re-exported for callers that treat this module as the submissions API.
export { answersToValues }

/** The one cycle currently accepting feedback, or null. */
export async function loadActiveCycle() {
  const { data, error } = await supabase
    .from('academic_cycles')
    .select('id, label, opens_at, closes_at')
    .eq('is_active', true)
    .maybeSingle()

  if (error) throw new Error(error.message)
  return data
}

export function cycleIsOpen(cycle) {
  if (!cycle) return false
  const now = Date.now()
  return now >= new Date(cycle.opens_at).getTime() &&
    now < new Date(cycle.closes_at).getTime()
}

/** FR-17: the signed-in user's submissions for a cycle, newest first. */
export async function loadMySubmissions(userId, cycleId) {
  const { data, error } = await supabase
    .from('responses')
    .select('id, program, course_title, submitted_at, updated_at')
    .eq('user_id', userId)
    .eq('cycle_id', cycleId)
    .order('updated_at', { ascending: false })

  if (error) throw new Error(error.message)
  return data ?? []
}

/**
 * Loads one response plus its answers, shaped into the form's value map.
 *
 * Answers are keyed by question_version_id. A stored answer whose version is no
 * longer any question's current version simply won't match a rendered field —
 * correct behaviour, since that wording was superseded (FR-31).
 */
export async function loadResponse(responseId, questions = null) {
  const { data: response, error } = await supabase
    .from('responses')
    .select('id, user_id, form_id, cycle_id, program, course_title, submitted_at, updated_at')
    .eq('id', responseId)
    .maybeSingle()

  if (error) throw new Error(error.message)
  if (!response) return null

  const { data: answers, error: aError } = await supabase
    .from('answers')
    .select('question_version_id, value_numeric, value_text, value_options')
    .eq('response_id', responseId)

  if (aError) throw new Error(aError.message)

  // Passing the questions lets answersToValues tell a single_select from a
  // one-choice multi_select by type instead of guessing from array length.
  const byVersionId = questions
    ? new Map(questions.map((q) => [q.versionId, q]))
    : null

  return { response, values: answersToValues(answers ?? [], byVersionId) }
}

/**
 * Creates or updates a submission (FR-12, FR-15, FR-16).
 *
 * The one-per-course rule lives in a unique index on
 * (user_id, cycle_id, course_key), where course_key is generated by Postgres.
 * We cannot upsert on a generated column, so:
 *   - editing an existing response -> update by id
 *   - new submission               -> insert, and translate a 23505 unique
 *     violation into a load-and-edit prompt rather than an opaque failure
 *
 * That keeps Postgres as the single source of truth for the rule: two tabs
 * racing the same course produce one row and one clear message, not a duplicate.
 */
export async function saveSubmission({
  responseId,
  userId,
  form,
  cycle,
  questions,
  values,
}) {
  const meta = {
    program: pickMeta(questions, values, PROGRAM_KEYS),
    course_title: pickMeta(questions, values, COURSE_KEYS),
  }

  let id = responseId

  if (id) {
    const { error } = await supabase
      .from('responses')
      .update(meta)
      .eq('id', id)
    if (error) throw translateSaveError(error)
  } else {
    const { data, error } = await supabase
      .from('responses')
      .insert({ user_id: userId, form_id: form.id, cycle_id: cycle.id, ...meta })
      .select('id')
      .single()
    if (error) throw translateSaveError(error)
    id = data.id
  }

  await writeAnswers(id, questions, values)
  return id
}

/**
 * Replaces the answer set for a response.
 *
 * Delete-then-insert rather than per-row upsert: a question that was answered
 * and is now blank must disappear, and the unique (response_id,
 * question_version_id) pair makes a partial upsert awkward. Both statements are
 * gated by the same RLS edit-window policy, so a closed cycle fails the delete
 * and leaves the stored answers untouched.
 */
async function writeAnswers(responseId, questions, values) {
  const rows = questions
    .map((q) => toAnswerRow(q, values[q.versionId]))
    .filter(Boolean)
    .map((row) => ({ ...row, response_id: responseId }))

  const { error: delError } = await supabase
    .from('answers')
    .delete()
    .eq('response_id', responseId)
  if (delError) throw translateSaveError(delError)

  if (rows.length === 0) return

  const { error: insError } = await supabase.from('answers').insert(rows)
  if (insError) throw translateSaveError(insError)
}

/** FR-16: a respondent may withdraw a mis-filed submission before close. */
export async function deleteSubmission(responseId) {
  const { error } = await supabase.from('responses').delete().eq('id', responseId)
  if (error) throw translateSaveError(error)
}

/**
 * Turns Postgres/PostgREST errors into something a respondent can act on.
 * `code` is preserved so callers can branch (the form offers "edit it instead"
 * on a duplicate).
 */
export function translateSaveError(error) {
  const code = error.code ?? ''
  let message = error.message ?? 'Something went wrong while saving.'

  if (code === '23505') {
    message =
      'You have already submitted feedback for this course in this cycle. ' +
      'Open your existing submission to change your answers.'
  } else if (code === '42501' || /row-level security/i.test(message)) {
    // The edit window closing mid-session is the common cause.
    message =
      'This feedback cycle is closed, so submissions can no longer be changed. ' +
      'Reload the page to see the latest status.'
  }

  const wrapped = new Error(message)
  wrapped.code = code
  return wrapped
}
